name: flutter_provider

version: 1.0.0+1  # Pastikan hanya ada satu kunci version

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Lato
      fonts:
        - asset: assets/assets/fonts/Lato-Regular.ttf
        - asset: assets/assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Anton
      fonts:
        - asset: assets/assets/fonts/Anton-Regular.ttf